In [72]:
import pickle

import matplotlib.pyplot as plt
import networkx as nx
import torch
from torch_geometric.loader import DataLoader, NeighborLoader
from torch_geometric.transforms import ToUndirected
from torch_geometric.utils.convert import to_networkx

In [29]:
def visualize_graph(data):
    nx_data = to_networkx(data.to_homogeneous())
    nx.draw(nx_data)
    plt.show()

___

In [70]:
pyg_data = pickle.load(open("../data/04_feature/users_rating_movies_network.pickle", "rb"))

pyg_data

HeteroData(
  movie={ x=[27321, 1129] },
  user={ x=[13322, 13322] },
  (user, rates, movie)={
    edge_index=[2, 2000000],
    edge_label=[2000000]
  }
)

In [73]:
pyg_data = ToUndirected()(pyg_data)
del pyg_data["movie", "rev_rates", "user"].edge_label  # Remove "reverse" label.

In [174]:
unique_user_node_id = torch.tensor(list(set(pyg_data[("user", "rates", "movie")].edge_index[0, :].tolist())))
unique_movie_node_id = torch.tensor(list(set(pyg_data[("user", "rates", "movie")].edge_index[1, :].tolist())))
# , ("movie", unique_movie_node_id)
m = NeighborLoader(
    pyg_data,
    batch_size=100,
    shuffle=False,
    num_neighbors={
        ("user", "rates", "movie"): [30, 1],
        ("movie", "rev_rates", "user"): [1, 30],
    },  # {key: [1] * 2 for key in pyg_data.edge_types},
    input_nodes=("user", unique_user_node_id)
)

In [175]:
m = iter(m)

In [178]:
nexteu = next(m)
print(nexteu)
print(nexteu["user"].input_id)
print(nexteu[("user", "rates", "movie")].edge_index)

HeteroData(
  movie={ x=[93, 1129] },
  user={
    x=[193, 13322],
    input_id=[100],
    batch_size=100
  },
  (user, rates, movie)={
    edge_index=[2, 93],
    edge_label=[93]
  },
  (movie, rev_rates, user)={ edge_index=[2, 100] }
)
tensor([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
        214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
        228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
        256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
        270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
        284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297,
        298, 299])
tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 129, 130, 131, 132, 133, 

In [156]:
nexteu = next(m)
print(nexteu)
print(nexteu["user"].input_id)

HeteroData(
  movie={ x=[88, 1129] },
  user={
    x=[183, 13322],
    input_id=[100],
    batch_size=100
  },
  (user, rates, movie)={
    edge_index=[2, 88],
    edge_label=[88]
  },
  (movie, rev_rates, user)={ edge_index=[2, 100] }
)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
